# Generated by Django 4.1.3 on 2022-11-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
