# Generated by Django 4.1.3 on 2022-12-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/no_image.jpg', upload_to='images/'),
        ),
    ]
